import { useEffect, useState } from 'react';
import { FaAward, FaCalendarCheck, FaSignOutAlt, FaUserFriends } from 'react-icons/fa';
import { api } from '../services/api';

const initial = { name: '', email: '', phone: '', password: '' };
export function VolunteerPage() {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState(initial); const [profile, setProfile] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const load = () => api.get('/volunteers/me').then(({ data }) => setProfile(data.data)).catch(() => localStorage.removeItem('fju_volunteer_token'));
  useEffect(() => { if (localStorage.getItem('fju_volunteer_token')) load(); }, []);
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const { data } = await api.post(`/volunteers/${mode === 'login' ? 'login' : 'register'}`, form); localStorage.setItem('fju_volunteer_token', data.data.token); await load(); } catch (err) { setError(err.response?.data?.message || 'Não foi possível concluir a solicitação.'); } finally { setLoading(false); } }
  if (profile) return <main className="volunteer-page"><section className="volunteer-hero"><p className="home-eyebrow">Portal do voluntário</p><h1>Olá, {profile.name.split(' ')[0]}!</h1><p>{profile.project?.name ? `Projeto: ${profile.project.name}` : 'Seu perfil FJU está ativo.'}</p><button onClick={() => { localStorage.removeItem('fju_volunteer_token'); setProfile(null); }}><FaSignOutAlt /> Sair</button></section><section className="volunteer-dashboard"><article><FaCalendarCheck /><strong>{profile.attendances.length}</strong><span>presenças confirmadas</span></article><article><FaAward /><strong>{profile.certificates.length}</strong><span>certificados recebidos</span></article><article><FaUserFriends /><strong>FJU</strong><span>comunidade em ação</span></article></section><section className="volunteer-history"><h2>Seu histórico</h2>{profile.attendances.length || profile.certificates.length ? <><div>{profile.attendances.map(item => <p key={item.id}>{item.event.title} — presença em {new Date(item.presentAt).toLocaleDateString('pt-BR')}</p>)}</div><div>{profile.certificates.map(item => <a key={item.id} href={item.fileUrl || '#'}>{item.title} — {new Date(item.issuedAt).toLocaleDateString('pt-BR')}</a>)}</div></> : <p>Suas presenças e certificados aparecerão aqui quando forem registrados pela coordenação.</p>}</section></main>;
  return <main className="volunteer-page volunteer-access"><section><p className="home-eyebrow">Sou voluntário</p><h1>Faça parte da FJU</h1><p>Crie seu perfil para acompanhar presenças, eventos e certificados.</p><div className="volunteer-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Entrar</button><button className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>Criar perfil</button></div><form onSubmit={submit}>{mode === 'register' && <><label>Nome completo<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>WhatsApp<input required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label></>}<label>E-mail<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Senha<input type="password" minLength="8" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<button disabled={loading}>{loading ? 'Aguarde…' : mode === 'login' ? 'Entrar no portal' : 'Criar meu perfil'}</button></form></section></main>;
}
